import {
  Monitor, ArrowUpRight, Globe, Shield, Key, KeyRound, Ticket, Mail,
  Database, Calendar, Activity, Network, Clock, Users, Boxes,
  GitBranch, FolderLock, Filter, Video, FileText, FileSignature,
  MonitorCheck, LayoutDashboard, BookOpen, FileCode,
} from "lucide-react";
import type { ComponentType } from "react";

export interface OpenSourceElement {
  icon: ComponentType<{ className?: string }>;
  title: string;
  description: string;
  details: string[];
}

export const elements: OpenSourceElement[] = [
  {
    icon: Monitor,
    title: "Data Centre Virtualisation",
    description: "XCP-ng — open-source Type-1 bare-metal virtualization platform replacing VMware ESXi/vSphere with full enterprise capabilities.",
    details: [
      "Based on Xen Project hypervisor with centralized VM and host management",
      "Clustering, live migration, snapshots, storage and network virtualization",
      "Managed through Xen Orchestra — agentless web-based management layer",
      "Established VMware-to-XCP-ng migration workflows (V2V tooling)",
      "Optional professional support from Vates",
      "Eliminates VMware licensing costs and vendor lock-in",
    ],
  },
  {
    icon: Key,
    title: "SSL/TLS Certificates",
    description: "Let's Encrypt — free, automated certificate authority delivering browser-trusted certificates through the ACME protocol.",
    details: [
      "Zero certificate cost with broad automation support",
      "Hands-off issuance, renewal, and revocation at scale",
      "Domain Validation (DV) for standard HTTPS use cases",
      "Portability and operational simplicity for large fleets",
      "90-day certificate lifetimes with automation-first design",
      "Commercial CAs remain relevant for OV/EV and premium support",
    ],
  },
  {
    icon: KeyRound,
    title: "Self Service Password Reset",
    description: "PWM — powerful open-source SSPR for LDAP directories, reducing helpdesk calls through secure self-service password management.",
    details: [
      "Supports eDirectory and Active Directory via LDAP",
      "Configurable verification methods including challenge/response",
      "Policy enforcement, auditing, and workflow configuration",
      "Notifications, extensibility, and on-premise hosting",
      "No recurring per-user licensing costs",
      "Codebase associated with OpenText Self Service Password Reset",
    ],
  },
  {
    icon: Ticket,
    title: "Support Ticketing",
    description: "Zammad — modern open-source helpdesk and ticketing platform comparable to Zendesk with self-hosted sovereignty.",
    details: [
      "Multi-channel intake: email, web forms, chat, phone, social",
      "Automation rules, triggers, macros, and templates",
      "Full-text search, tagging, SLA handling, and reporting",
      "Strong REST API for ITSM/CRM workflow integration",
      "Branded and customized to fit organizational processes",
      "Enterprise-grade experience without vendor lock-in",
    ],
  },
  {
    icon: Mail,
    title: "Enterprise E-Mail",
    description: "Kolab — free open-source enterprise e-mail and groupware platform as a self-hosted alternative to Microsoft Exchange.",
    details: [
      "Full groupware: e-mail, calendars, contacts, tasks, notes",
      "Standard protocols: IMAP/SMTP, CalDAV/CardDAV, ActiveSync",
      "Familiar clients: Outlook, Thunderbird, native mobile apps",
      "Modern Roundcube-based web client for browser access",
      "Shared folders and calendars with granular access control",
      "Integrated anti-spam/anti-virus with optional extensions",
    ],
  },
  {
    icon: Database,
    title: "Databases",
    description: "MariaDB — mature enterprise-grade open-source relational database as a strategic alternative to Oracle and proprietary databases.",
    details: [
      "Fork of MySQL with independent evolution and compatibility",
      "Advanced replication, clustering, encryption, and auditing",
      "Improved optimizer and storage engine choices",
      "Practical drop-in replacement for Oracle in many use cases",
      "Lower total cost of ownership with greater portability",
      "Strong performance, security features, and high availability",
    ],
  },
  {
    icon: Calendar,
    title: "Events Management",
    description: "Indico — open-source event management platform from CERN for planning and running events of any size.",
    details: [
      "End-to-end: event websites, registration, attendance management",
      "Abstract/paper submission and reviewing workflows",
      "Agenda, session scheduling, and speaker management",
      "Room booking integration and email notifications",
      "Post-event materials publishing and full control over data",
      "LDAP/SSO integration for on-premise deployment",
    ],
  },
  {
    icon: Activity,
    title: "SIEM & XDR",
    description: "Wazuh — free open-source XDR + SIEM platform combining endpoint detection with centralized log collection and correlation.",
    details: [
      "Lightweight agents for endpoint telemetry and detection",
      "Centralized log collection with correlation rules and alerting",
      "Compliance monitoring, file integrity, and vulnerability detection",
      "MITRE ATT&CK framework mapping for faster investigation",
      "Dashboards and search via Elastic (ELK) stack",
      "Vendor-neutral with optional commercial support available",
    ],
  },
  {
    icon: Network,
    title: "Firewall, VPN, IDS & Reverse Proxy",
    description: "pfSense — open-source FreeBSD-based firewall consolidating Firewall + VPN + IDS/IPS + Reverse Proxy on commodity hardware.",
    details: [
      "Stateful firewalling, NAT, multi-WAN, traffic shaping/QoS",
      "IPsec, OpenVPN, and WireGuard VPN support",
      "IDS/IPS via Snort or Suricata add-ons",
      "HAProxy and Squid for reverse proxy and TLS termination",
      "Centralized web management for branch and remote access",
      "Enterprise-grade security without per-user licensing",
    ],
  },
  {
    icon: Clock,
    title: "Time Management",
    description: "Kimai — professional open-source web-based time tracking and timesheet system for teams and organizations.",
    details: [
      "Multi-user and multi-team time entry with project structures",
      "Timers and punch-in/punch-out with flexible rates",
      "Detailed reports and exports for billing and insight",
      "Built-in invoicing and JSON API for integrations",
      "LDAP/SAML authentication and 2FA support",
      "No per-user subscription model",
    ],
  },
  {
    icon: Users,
    title: "Customer Relationship Management",
    description: "SuiteCRM — enterprise-ready open-source CRM covering the full customer lifecycle from leads to invoicing.",
    details: [
      "Leads, accounts, opportunities, campaigns, cases/support",
      "Quotes, invoices, workflows, reporting, and self-service portals",
      "Fork of last open-source SugarCRM Community Edition",
      "AGPL licensed with ongoing maintenance and functionality",
      "Self-hosted for data ownership and deep customization",
      "Dashboards, automation, and integration capabilities",
    ],
  },
  {
    icon: Boxes,
    title: "Enterprise Resource Management",
    description: "Dolibarr — modular open-source ERP and CRM for managing core business operations without heavyweight complexity.",
    details: [
      "Customer and supplier management with quotations and sales orders",
      "Invoicing, payments, product and service catalogs",
      "Stock/warehouse control, purchasing, and agenda/calendar",
      "Accounting/finance with additional modules available",
      "Highly configurable for SMEs and public-sector organizations",
      "Single platform to track operational workflows end-to-end",
    ],
  },
  {
    icon: GitBranch,
    title: "DevOps",
    description: "GitLab — comprehensive DevOps platform managing the full software lifecycle from planning through deployment.",
    details: [
      "Git-based repository management with merge requests and code review",
      "Built-in CI/CD pipelines for automated builds, tests, deployments",
      "Role-based access control, audit logs, and governance",
      "Dependency scanning, SAST/DAST, and vulnerability management",
      "Self-hosted on-premise for data sovereignty and controlled access",
      "Cloud service or self-hosted deployment options",
    ],
  },
  {
    icon: FolderLock,
    title: "Secure File Management",
    description: "Nextcloud — self-hosted file management and secure sharing platform as an alternative to OneDrive, Google Drive, Dropbox.",
    details: [
      "Secure sync and share with granular permissions",
      "Expiring links, end-to-end or server-side encryption",
      "File versioning, recovery, and detailed auditing",
      "Online document editing via Collabora/OnlyOffice integrations",
      "Calendaring, contacts, chat/video, and workflow automation",
      "Enterprise-grade secure sharing with full data sovereignty",
    ],
  },
  {
    icon: Filter,
    title: "E-Mail Filtering",
    description: "ASSP — free open-source SMTP proxy for spam and malicious e-mail filtering before it reaches users.",
    details: [
      "Self-learning Bayesian and Hidden Markov Model analysis",
      "Auto-whitelisting, greylisting, DNSBL/DNSWL and URIBL lookups",
      "SPF and sender/authentication controls",
      "Virus scanning, attachment blocking, and backscatter protection",
      "Policy-based controls for inbound filtering",
      "No per-user subscription costs with on-premise control",
    ],
  },
  {
    icon: Video,
    title: "Video Conferencing",
    description: "BigBlueButton — open-source virtual classroom and video conferencing platform designed for teaching and collaboration.",
    details: [
      "Real-time audio/video, screen sharing, whiteboard annotation",
      "Public/private chat, polling, breakout rooms, shared notes",
      "Recording and learning analytics for post-event review",
      "Deep integration with Moodle and Canvas LMS",
      "Self-hosted on premise for data sovereignty and security",
      "Used globally by universities, schools, and large organizations",
    ],
  },
  {
    icon: LayoutDashboard,
    title: "Office Productivity",
    description: "LibreOffice — full-featured open-source office suite as a direct replacement for Microsoft Office.",
    details: [
      "Writer, Calc, Impress, Draw, Base, and Math applications",
      "Strong compatibility with DOCX, XLSX, and PPTX formats",
      "ODF (OpenDocument Format) as native format for portability",
      "No per-user subscription licensing at scale",
      "Professional templates, advanced features, and macros",
      "Digital sovereignty through open standards and local support",
    ],
  },
  {
    icon: FileText,
    title: "PDF Management",
    description: "PDF24 — free Windows-focused PDF creation and editing platform for common PDF workflows without Adobe Acrobat costs.",
    details: [
      "PDF creation via virtual PDF printer driver",
      "Merge, split, compress, convert, and watermark documents",
      "Signing, encryption, OCR, and basic editing capabilities",
      "Free of charge for companies with no licensing required",
      "Local/offline processing for improved privacy and control",
      "Freeware leveraging open-source components",
    ],
  },
  {
    icon: Globe,
    title: "Operating Systems",
    description: "Linux distributions (SUSE, Debian, Ubuntu) and FreeBSD — UNIX-like operating systems for server and cloud infrastructure.",
    details: [
      "Stability, security, and multi-user capabilities",
      "UNIX/POSIX toolset: shell, permissions, process model, networking",
      "Power web servers, databases, firewalls, storage, and virtualization",
      "Open standards with strong automation and hardware support",
      "Freedom from vendor lock-in compared to proprietary UNIX",
      "Strategic alternative for modern infrastructure foundations",
    ],
  },
  {
    icon: FileCode,
    title: "Content Management System",
    description: "Joomla — mature open-source CMS for building websites, intranets, and web applications with flexible customization.",
    details: [
      "Templates, extensions, and modules for web development",
      "User management, multilingual sites, and access control (ACL)",
      "Content workflows, menus, and media management out of the box",
      "Balance between ease of use and customization depth",
      "Large ecosystem with strong standards support",
      "Scalable, secure, and cost-effective without vendor lock-in",
    ],
  },
  {
    icon: BookOpen,
    title: "Learning Management System",
    description: "Canvas — modern LMS used by universities, schools, and training organizations to deliver and manage digital learning.",
    details: [
      "Course and content management with assignments and quizzes",
      "Grading with rubrics, discussion forums, and analytics",
      "Mobile access with intuitive user experience",
      "LTI, SCORM, and SIS connectivity for data integration",
      "Third-party learning tool plug-in support",
      "Blended or fully online learning environments",
    ],
  },
];
