"use client";

import { LegalLayout } from "@/components/shared/LegalLayout";

export function PrivacyClient() {
  return (
    <LegalLayout title="Privacy Policy" lastUpdated="26 March 2023" heroImage="/legal/privacy-hero.jpg">
      <div className="space-y-8 text-[var(--netcb-text-muted)] leading-relaxed">
        <div className="space-y-4">
          <p>This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
          <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
        </div>

        <section>
          <h2 className="text-xl font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-4">Interpretation and Definitions</h2>
          <h3 className="text-lg font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-3">Interpretation</h3>
          <p className="mb-4">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
          <h3 className="text-lg font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-3">Definitions</h3>
          <p className="mb-3">For the purposes of this Privacy Policy:</p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li><strong className="text-[var(--netcb-text)]">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            <li><strong className="text-[var(--netcb-text)]">Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to NETCB ZA (PTY) LTD, Innovation Centre, 1 Mark Shuttleworth Street, The Innovation Hub, Pretoria, 0087.</li>
            <li><strong className="text-[var(--netcb-text)]">Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for the election of directors or other managing authority.</li>
            <li><strong className="text-[var(--netcb-text)]">Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong className="text-[var(--netcb-text)]">Website</strong> refers to NETCB, accessible from <a href="https://www.netcb.com" target="_blank" rel="noopener noreferrer" className="text-[var(--netcb-accent)] hover:underline">https://www.netcb.com</a></li>
            <li><strong className="text-[var(--netcb-text)]">Service</strong> refers to the Website.</li>
            <li><strong className="text-[var(--netcb-text)]">Country</strong> refers to: South Africa</li>
            <li><strong className="text-[var(--netcb-text)]">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
            <li><strong className="text-[var(--netcb-text)]">Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
            <li><strong className="text-[var(--netcb-text)]">Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong className="text-[var(--netcb-text)]">Cookies</strong> are small files that are placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong className="text-[var(--netcb-text)]">Device</strong> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
            <li><strong className="text-[var(--netcb-text)]">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-4">Collecting and Using Your Personal Data</h2>
          <h3 className="text-lg font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-3">Types of Data Collected</h3>

          <h4 className="font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-2">Personal Data</h4>
          <p className="mb-3">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul className="list-disc list-inside space-y-1 ml-4 mb-4">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
          </ul>

          <h4 className="font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-2">Usage Data</h4>
          <div className="space-y-3">
            <p>Usage Data is collected automatically when using the Service.</p>
            <p>Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device&apos;s unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
            <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-4">Tracking Technologies and Cookies</h2>
          <div className="space-y-3">
            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</p>
            <p>You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</p>
            <p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser. Learn more about cookies in the &quot;What Are Cookies&quot; article.</p>
          </div>
          <p className="mt-3 mb-4">We use both session and persistent Cookies for the purposes set out below:</p>

          <div className="glass rounded-xl p-6 mb-4">
            <h4 className="font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-2">Necessary / Essential Cookies</h4>
            <p className="text-sm mb-1"><strong className="text-[var(--netcb-text)]">Type:</strong> Session Cookies</p>
            <p className="text-sm mb-1"><strong className="text-[var(--netcb-text)]">Administered by:</strong> Us</p>
            <p className="text-sm">Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
          </div>

          <div className="glass rounded-xl p-6 mb-4">
            <h4 className="font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-2">Cookies Policy / Notice Acceptance Cookies</h4>
            <p className="text-sm mb-1"><strong className="text-[var(--netcb-text)]">Type:</strong> Persistent Cookies</p>
            <p className="text-sm mb-1"><strong className="text-[var(--netcb-text)]">Administered by:</strong> Us</p>
            <p className="text-sm">Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
          </div>

          <div className="glass rounded-xl p-6">
            <h4 className="font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-2">Functionality Cookies</h4>
            <p className="text-sm mb-1"><strong className="text-[var(--netcb-text)]">Type:</strong> Persistent Cookies</p>
            <p className="text-sm mb-1"><strong className="text-[var(--netcb-text)]">Administered by:</strong> Us</p>
            <p className="text-sm">Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
          </div>

          <p className="mt-4">For more information about the cookies we use and your choices regarding cookies, please visit our <a href="/legal/cookies" className="text-[var(--netcb-accent)] hover:underline">Cookies Policy</a>.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-4">Use of Your Personal Data</h2>
          <p className="mb-3">The Company may use Personal Data for the following purposes:</p>
          <ul className="list-disc list-inside space-y-2 ml-4 mb-4">
            <li>To provide and maintain our Service, including monitoring the usage of our Service.</li>
            <li>To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
            <li>For the performance of a contract: the development, compliance, and undertaking of the purchase contract for the products, items, or services You have purchased or of any other contract with Us through the Service.</li>
            <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
            <li>To provide You with news, special offers, and general information about other goods, services, and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
            <li>To manage Your requests: To attend to and manage Your requests to Us.</li>
          </ul>
          <p className="mb-3">We may share your personal information in the following situations:</p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li><strong className="text-[var(--netcb-text)]">With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
            <li><strong className="text-[var(--netcb-text)]">For Business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.</li>
            <li><strong className="text-[var(--netcb-text)]">With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners, or other companies that We control or that are under common control with Us.</li>
            <li><strong className="text-[var(--netcb-text)]">With Business partners:</strong> We may share Your information with Our business partners to offer You certain products, services, or promotions.</li>
            <li><strong className="text-[var(--netcb-text)]">With other users:</strong> when You share personal information or otherwise interact in public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures, and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-4">Retention of Your Personal Data</h2>
          <div className="space-y-3">
            <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
            <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-4">Transfer of Your Personal Data</h2>
          <div className="space-y-3">
            <p>Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>
            <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
            <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-4">Disclosure of Your Personal Data</h2>
          <h3 className="text-lg font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-3">Business Transactions</h3>
          <p className="mb-4">If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
          <h3 className="text-lg font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-3">Law enforcement</h3>
          <p className="mb-4">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
          <h3 className="text-lg font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-3">Other legal requirements</h3>
          <p className="mb-3">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-4">Security of Your Personal Data</h2>
          <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-4">Children&apos;s Privacy</h2>
          <div className="space-y-3">
            <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
            <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent&apos;s consent before We collect and use that information.</p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-4">Links to Other Websites</h2>
          <div className="space-y-3">
            <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third-party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
            <p>We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-4">Changes to this Privacy Policy</h2>
          <div className="space-y-3">
            <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
            <p>We will let you know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
            <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-semibold font-[var(--font-display)] text-[var(--netcb-text)] mb-4">Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, you can contact us on <a href="mailto:privacy@netcb.com" className="text-[var(--netcb-accent)] hover:underline">privacy@netcb.com</a></p>
        </section>
      </div>
    </LegalLayout>
  );
}
